services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./portfolio.db:/app/portfolio.db.rw
    environment:
      FLASK_APP: main
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080", "--reload"]
