services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: main
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_RUN_FROM_WAITRESS: 1
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: portfolio
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: portfolio
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080", "--reload"]
